### ISSUE TITLE
Setting up accounts and ISO files

### ISSUE THREAD

**Issue by JuliaJin05** [cmu-sei/foundry-appliance#53]
Hi,

I have the OVA file set up, but I just can not figure out how to setup the accounts. Has anyone been able to successfully integrate identity with a OAuth2/OIDC application?

Also, where do we upload our own ISO files for Gameboard? It seems like we can not select a file to upload onto it. 

Thank you

**Comment by sei-jbooz** [comment]
Hi JuliaJin05, 

You can find more information about how to use Identity Server by viewing the [application documentation here](https://cmu-sei.github.io/foundry-docs/identity/). 

Gameboard does not support uploading ISO files. For more information how to use Gameboard, you can view the [application documentation here](https://cmu-sei.github.io/foundry-docs/gameboard/)

**Comment by JuliaJin05** [comment]
Thanks for the link,
I was wondering if this was a glitch or am I supposed to change some setting. Whenever I login after I setup the 2FA, the "123456" code works for normal user accounts.

**Comment by sei-jbooz** [comment]
123456 is configured to be an "override code" in the Identity Application in this appliance. You can learn more about Override Codes in Identity on [this page](https://cmu-sei.github.io/foundry-docs/identity/accounts/).

**Comment by JuliaJin05** [comment]
Sorry, I don't know if I'm misunderstanding something or looking over it, but how are we even supposed to generate the virtual machines? How do we even connect TopoMojo to a hypervisor to host machines?

**Comment by sei-jbooz** [comment]
You can find more information about configuration TopoMojo in the [TopoMojo repository](https://github.com/cmu-sei/topomojo) and [TopoMojo Helm Chart](https://github.com/cmu-sei/helm-charts/blob/b8f349064d9a89f737cf2394210697715c0a5e22/charts/topomojo/values.yaml)

**Comment by JuliaJin05** [comment]
Hello! I hope you are doing well.

I was hoping you could please answer a question I had about the mock hypervisor. If I understand correctly, when I deploy a machine in TopoMojo, it should automatically work after I create a template? If so, I remember there being an option to use the gui to change the settings, but now when I check I only see some json type of structure? Also, when you do use the gui, should you be able to just select one of the default isos and test the VM deployment?

Thank you so much!
<img width="784" alt="Screenshot 2024-04-05 at 11 46 56 AM" src="https://github.com/cmu-sei/foundry-appliance/assets/95390384/241e8117-cfd0-4908-a152-06bd7370224d">

**Comment by sei-jbooz** [comment]
Hello, 

The TopoMojo Mock Hypervisor is not a real hypervisor that can deploy Virtual Machines (VMs). It is just a mock way to run TopoMojo without a real hypervisor in case you need to do some testing that doesn't require VMs. 

You can find more information about how to use TopoMojo in the [documentation here](https://cmu-sei.github.io/foundry-docs/topomojo/).

**Comment by JuliaJin05** [comment]
Okay, thanks.

Also, I was trying to upload an ISO file, however, it did not go through. I'll upload it and it does not pop up as an option. Am I doing this wrong or is it some glitch?

**Comment by sei-jbooz** [comment]
Uploading ISOs to TopoMojo requires a real hypervisor with an NFS datastore attached to it. You would set this line in the Helm Chart: https://github.com/cmu-sei/helm-charts/blob/6ba2fc6632315ae33e8f1fe24c86fc2b5772883c/charts/topomojo/values.yaml#L189

**Comment by JuliaJin05** [comment]
I am running ESXi with vSphere and I am having trouble finding where to put in the credentials in order to connect the vSphere to foundry appliance. Do you have a guide on this?

**Comment by sei-jbooz** [comment]
These settings are configured via Helm Chart: https://github.com/cmu-sei/helm-charts/blob/6ba2fc6632315ae33e8f1fe24c86fc2b5772883c/charts/topomojo/values.yaml#L183

**Comment by JuliaJin05** [comment]
I am having trouble connecting the servers together. In the VMStore and ISOstore, after the brackets, there is the pathway "topomojo/". I am wondering if this is something that the foundry appliance will make on its own or something I'm supposed to find within vSphere. I have settings in everything from the user to diskstore except the pool path and nothing pops up in the local ISOs setting in the templates. Is there more that I need to configure or am I doing something wrong? Thanks!
<img width="285" alt="image" src="https://github.com/cmu-sei/foundry-appliance/assets/95390384/ff9fb89b-9eca-4c54-9b61-c30d117b91c8">
